name: "Create A Catalog Zarr Store"

on:
  workflow_dispatch:
    inputs:
      recipe_id:
        description: 'The id of a single recipe to submit to Dataflow'
        required: true

env:
  RECIPE_ID: ${{ github.event.inputs.recipe_id }}
jobs:
  create-catalog-zarr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install zarr gcsfs ruamel.yaml xarray
      - run: |
          python scripts/create_catalog_zarr.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"